format_version: 10
pipelines:
  pipeline2:
    group: New-Pipiline-Test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      exp-material:
        git: https://github.com/RohitPhargade/Aerospike-Client-Exp-Demo.git
        username: phargaderohit9696@gmail.com
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:426ni8BbY/IxYl9jACpCjw==:o6ZOrsV7HSpa9plU1xRTPQ==
    stages:
      - stage2:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            jobname2:
              timeout: 0
              environment_variables:
                varrohit: rohitph
              tasks:
                - exec:
                    arguments:
                      - build
                    command: ./gradlew
                    run_if: passed
    parameters:
      varrohit: ok value